on:
  push:
    branches:
      - main
      - master
    tags:
      -'*'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/install-r-dependencies@master
      - name: Install dependencies
              run: |
                install.packages("remotes")
                remotes::install_deps(dependencies = TRUE)
                install.packages("pkgdown")
                remotes::install_github("ModelOriented/DrWhyTemplate")
                install.packages("textshaping")
              shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
